# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: black
      name: Python Formatting
      language: system
      types: [python]
      entry: ./dev.sh server-exec /bin/sh -c 'cd .. && black "$@"' --
    - id: flake8
      name: Style Guide Checking
      language: system
      types: [python]
      entry: ./dev.sh server-exec /bin/sh -c 'cd .. && flake8 --config setup.cfg "$@"' --
