apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  labels:
    tier: startup
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    # The next line is used for development so that you can see the logs
    # from this job, as the job will not be deleted upon completion.
    # In a non-prod env, consider 'hook-succeeded' instead.
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: migration-job
      labels:
        tier: startup
    spec:
      restartPolicy: Never
      volumes:
        - name: host-project
          hostPath:
            path: {{ .Values.projectDir }}
      containers:
        - name: migration-job
          image: {{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          workingDir: /opt/server
          command: ["python"]
          args: ["manage.py", "migrate", "--noinput"]
          volumeMounts:
            - name: host-project
              mountPath: /opt/server/
