apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    tier: server

