apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-server
  labels:
    tier: server
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: server
  template:
    metadata:
      labels:
        tier: server
    spec:
      securityContext:
        # The default behavior of your node is to run as root, but that is undesirable, even in a dev environment,
        # because root in the container is root on the node (your machine). In dev we still need the pod user to
        # have some permissions, most notably the ability to write to the file system, because we're actually
        # running our pre-commit hooks *inside* the pod. Therefore, we're going to run the server pod, and your code
        # as the user that runs helm3. In a production version of this template, you'd probably want to run as
        # something more secure.
        runAsUser: {{ .Values.uid }}
        fsGroup: {{ .Values.uid }}
        runAsNonRoot: true
      volumes:
        - name: host-project
          hostPath:
            path: "{{ .Values.projectDir }}"
        - name: database-secrets
          secret:
            secretName: database-credentials
        - name: app-secrets
          secret:
            secretName: app-secrets
      containers:
        - name: server
          image: "{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          workingDir: /opt/project/server
          command: ["python"]
          args: ["manage.py", "runserver_plus", "0.0.0.0:8000"]
          env:
            - name: SECRETS_ROOTPATH
              value: "{{ .Values.secrets.rootPath }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: host-project
              mountPath: /opt/project/
            - name: database-secrets
              mountPath: "{{ .Values.secrets.rootPath }}/database-secrets"
              readOnly: true
            - name: app-secrets
              mountPath: "{{ .Values.secrets.rootPath }}/app-secrets"
              readOnly: true
