name: push-actions
on: [push]
jobs:
  check-files:
    name: "Check Files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r deploy/docker/development-server/hook-requirements.txt
      - run: isort --check-only .
      - run: black .
      - run: flake8 --config setup.cfg .
      - run: mypy .
      - run: find . -type f -name *.sh | xargs shellcheck